sudo: required
services:
  - docker

before_install: 
    - docker build -t mdubbed/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mdubbed/docker-react npm run test -- --coverage


